name: Reddit Safe Automation

on:
  schedule:
    # Run twice daily: 09:00 and 21:00 UTC
    - cron: '0 9,21 * * *'
  workflow_dispatch:  # Allow manual triggers

jobs:
  reddit-automation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw requests
      
      - name: Run Reddit automation
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          LINK_POLICY: ${{ secrets.LINK_POLICY }}
        run: |
          python reddit_automation.py
      
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reddit-automation-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 30
